### ISSUE TITLE
Need clarification -- how can I use/configure the library to work only for adjectives?

### ISSUE THREAD

**Issue by IGMontero** [mistval/jp-verb-conjugator#5]
As the question states, I don't know how to make it only match WordType.ADJECTIVE. 
Any clarification is highly appreciated!

**Comment by mistval** [comment]
Hi,

This module only supports verbs. There is WIP adjective support in it, but it's not enabled and I don't remember how good of a state it's in since I haven't touched it in 6 years.

If you would like to try it, you can try changing [this line](https://github.com/mistval/jp-verb-deconjugator/blob/e13c0371a4ddb386f18da53eb83a296f24a61a6c/index.js#L234) to `const isDictionaryForm = wordType === WordType.ADJECTIVE;`

If it works decently well, I would welcome a pull request to add an `onlyAdjectives` option to the `unconjugate()` function that changes the behavior of that line of code accordingly.
